// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWpMlYDa7cCCjVJNbK2Qyh4oJZvNvt5SI',
    appId: '1:969082493904:web:fc24180004fae527dcb7d5',
    messagingSenderId: '969082493904',
    projectId: 'community-safety-app-e8707',
    authDomain: 'community-safety-app-e8707.firebaseapp.com',
    storageBucket: 'community-safety-app-e8707.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu7r7jQk8andtd0z_URdNFtnJBdWcnkIw',
    appId: '1:969082493904:android:a40ce599209f5549dcb7d5',
    messagingSenderId: '969082493904',
    projectId: 'community-safety-app-e8707',
    storageBucket: 'community-safety-app-e8707.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBOYdP7isIwyoMt6RaBQRjCUa52vVbpPQ',
    appId: '1:969082493904:ios:fc184fc5dc1d21fadcb7d5',
    messagingSenderId: '969082493904',
    projectId: 'community-safety-app-e8707',
    storageBucket: 'community-safety-app-e8707.firebasestorage.app',
    iosClientId: '969082493904-pcr4qpppsj7mjrlffdhjodqq4btsipqb.apps.googleusercontent.com',
    iosBundleId: 'com.example.safetyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBOYdP7isIwyoMt6RaBQRjCUa52vVbpPQ',
    appId: '1:969082493904:ios:fc184fc5dc1d21fadcb7d5',
    messagingSenderId: '969082493904',
    projectId: 'community-safety-app-e8707',
    storageBucket: 'community-safety-app-e8707.firebasestorage.app',
    iosClientId: '969082493904-pcr4qpppsj7mjrlffdhjodqq4btsipqb.apps.googleusercontent.com',
    iosBundleId: 'com.example.safetyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWpMlYDa7cCCjVJNbK2Qyh4oJZvNvt5SI',
    appId: '1:969082493904:web:589cbada681ea3dfdcb7d5',
    messagingSenderId: '969082493904',
    projectId: 'community-safety-app-e8707',
    authDomain: 'community-safety-app-e8707.firebaseapp.com',
    storageBucket: 'community-safety-app-e8707.firebasestorage.app',
  );
}
